Repository code-4-u/beauty-4-u-FE, pull requests merged in 2024-12, with the labels that each got.

#3 feat: 라우터 구현
  package-lock.json
  package.json
  src/App.vue
  src/main.js
  src/router/index.js
  src/views/Home.vue
Labels: feat

#4 feat: Header, Footer 구현
  package-lock.json
  package.json
  src/App.vue
  src/assets/css/resetcss.css
  src/components/common/Footer.vue
  src/components/common/Header.vue
  src/components/test.vue
  src/main.js
  src/plugins/fontawesome.js
Labels: feat

#6 chore: Pinia 연동 및 설정
  package-lock.json
  package.json
  src/main.js
Labels: chore

#12 feat: 아이디 찾기, 비밀번호 재발급 구현
  package-lock.json
  package.json
  src/assets/css/resetcss.css
  src/components/common/Header.vue
  src/components/user/FindIdModal.vue
  src/components/user/ResetPasswordModal.vue
  src/views/user/Login.vue
  vite.config.js
Labels: feat, chore

#13 feat: 아이디 찾기, 비밀번호 재발급 api 연동
  src/assets/css/resetcss.css
  src/components/common/LoadingSpinner.vue
  src/components/user/FindIdModal.vue
  src/components/user/ResetPasswordModal.vue
Labels: feat, refactor

#18 feat: 고객 상세 조회 화면 구현
  package-lock.json
  package.json
  src/App.vue
  src/components/Customer/CustomerDetailComponent.vue
  src/components/Customer/CustomerListFilterModal.vue
  src/components/Customer/CustomerOrderListFilterModal.vue
  src/components/Customer/CustomerPurchaseComponent.vue
  src/components/common/CustomerNav.vue
  src/main.js
  src/router/customer.js
  src/stores/customerPinia.js
  src/stores/util.js
  src/views/customer/CustomerCommonDetail.vue
  src/views/customer/CustomerHome.vue
  src/views/customer/CustomerList.vue
Labels: feat, refactor, chore

#20 feat: 메인화면 틀 구성
  package-lock.json
  package.json
  src/components/Home/HomeSideBar.vue
  src/views/Home.vue
Labels: feat

#24 feat: 공지사항 화면 구현, 헤더 수정
  src/components/Home/SimpleInform.vue
  src/components/Home/SimpleQAndA.vue
  src/components/common/BoardNav.vue
  src/components/common/Header.vue
  src/router/board.js
  src/router/index.js
  src/router/inform.js
  src/views/board/BoardHome.vue
  src/views/board/FAQList.vue
  src/views/board/InformList.vue
  src/views/board/QAndAList.vue
Labels: feat, refactor

#28 feat: 마이페이지 및 비밀번호 수정 모달 구현
  src/components/common/UserNav.vue
  src/components/user/UpdatePasswordModal.vue
  src/router/index.js
  src/router/user.js
  src/views/user/MyPage.vue
  src/views/user/UserHome.vue
Labels: feat, refactor

#30 feat: goods 상품조회, 리뷰조회 화면 임시 구현
  src/components/common/Header.vue
  src/router/goods.js
  src/router/index.js
  src/views/Home.vue
  src/views/goods/GoodsHome.vue
  src/views/goods/GoodsList.vue
  src/views/goods/GoodsNav.vue
  src/views/goods/Review.vue
Labels: fix, feat, chore

#32 chore: chat 화면 세팅
  package-lock.json
  package.json
  src/router/chat.js
  src/router/index.js
  src/views/chat/ChatHome.vue
  vite.config.js
Labels: chore

#33 fix: index.js 오류 수정
  src/router/index.js
Labels: fix

#35 feat: 신규 계정 등록 화면 구현
  src/assets/css/resetcss.css
  src/components/admin/CreateUserModal.vue
  src/components/common/AdminNav.vue
  src/plugins/fontawesome.js
  src/router/admin.js
  src/router/index.js
  src/views/admin/AdminHome.vue
  src/views/admin/UserList.vue
Labels: feat

#36 feat: 공지사항 상세 조회 화면 구현
  src/components/board/inform/InformDetail.vue
  src/router/board.js
  src/views/board/InformList.vue
Labels: feat

#42 feat: 회원 활성화, 비활성화 api 연동
  src/views/admin/UserList.vue
Labels: feat

#44 feat: 리뷰 조회 화면 구현
  src/router/goods.js
  src/views/goods/GoodsNav.vue
  src/views/goods/Review.vue
Labels: feat

#41 feat: 일정 등록, 수정, 삭제, 목록 조회 api 연동
  src/components/Home/HomeSideBar.vue
  src/views/Home.vue
Labels: feat

#47 feat: FAQ 화면 구현
  src/App.vue
  src/components/common/Header.vue
  src/views/Home.vue
  src/views/board/FAQList.vue
Labels: feat, refactor

#49 feat: 팀스페이스 기본 구조 구현
  src/components/common/TeamSpaceNav.vue
  src/router/index.js
  src/router/teamspace.js
  src/views/teamspace/Scrap.vue
  src/views/teamspace/TeamSpaceHome.vue
Labels: feat

#50 feat: 공지사항 화면 구현
  package-lock.json
  package.json
  src/components/board/inform/BoardEditor.vue
  src/components/board/inform/InformDetail.vue
  src/components/board/inform/InformSave.vue
  src/components/board/inform/informUpdate.vue
  src/plugins/fontawesome.js
  src/router/board.js
  src/views/board/InformList.vue
Labels: feat

#52 feat: 상품 조회 화면 구현
  src/router/goods.js
  src/views/goods/GoodsList.vue
Labels: feat

#53 feat, refactor: 공지사항 관련 리팩토링 및 구현
  package-lock.json
  package.json
  src/components/Home/SimpleInform.vue
  src/components/Home/SimpleQNA.vue
  src/components/board/ImageManagement.vue
  src/components/board/editor/MenuBar.vue
  src/components/board/editor/MenuItem.vue
  src/components/board/inform/BoardEditor.vue
  src/components/board/inform/InformDetail.vue
  src/components/board/inform/InformSave.vue
  src/components/board/inform/informUpdate.vue
  src/components/common/BoardNav.vue
  src/components/common/Header.vue
  src/router/board.js
  src/views/board/InformList.vue
  src/views/board/QNAList.vue
Labels: feat, refactor

#60 refactor: 메인 화면 리팩토링
  src/App.vue
  src/components/home/HomeSideBar.vue
  src/views/Home.vue
Labels: feat, refactor

#62 feat: 액세스토큰에 부서, 직급, 회원이름 추가
  src/stores/auth.js
Labels: feat

#64 refactor: 헤더 리팩토링
  src/components/board/faq/FaqDetail.vue
  src/components/board/faq/FaqSave.vue
  src/components/board/faq/FaqUpdate.vue
  src/components/board/inform/InformDetail.vue
  src/components/board/inform/InformSave.vue
  src/components/board/inform/InformUpdate.vue
  src/components/board/qna/QnaDetail.vue
  src/components/board/qna/QnaSave.vue
  src/components/board/qna/QnaUpdate.vue
  src/components/common/AdminNav.vue
  src/components/common/BoardNav.vue
  src/components/common/Header.vue
  src/components/common/UserNav.vue
  src/components/customer/CustomerDetailComponent.vue
  src/components/customer/CustomerListFilterModal.vue
  src/components/customer/CustomerOrderListFilterModal.vue
  src/components/customer/CustomerPurchaseComponent.vue
  src/components/home/SimpleInform.vue
  src/components/home/SimpleQNA.vue
  src/plugins/fontawesome.js
  src/router/admin.js
  src/router/board.js
  src/router/chat.js
  src/router/customer.js
  src/router/index.js
  src/router/teamspace.js
  src/router/user.js
  src/stores/auth.js
  src/views/admin/AdminHome.vue
  src/views/admin/UserList.vue
  src/views/board/BoardHome.vue
  src/views/board/FaqList.vue
  src/views/board/InformList.vue
  src/views/board/QnaList.vue
  src/views/customer/CustomerList.vue
  src/views/user/UserHome.vue
Labels: feat, refactor

#68 refactor: 디자인 리팩토링
  src/App.vue
  src/router/index.js
  src/views/Home.vue
  src/views/board/FaqList.vue
  src/views/board/InformList.vue
  src/views/board/QnaList.vue
Labels: refactor

#73 feat: 프로모션 관련 화면 구현
  src/components/common/Header.vue
  src/components/common/TeamSpaceNav.vue
  src/components/goods/GoodsAnalysis.vue
  src/components/goods/GoodsList.vue
  src/components/goods/GoodsSearch.vue
  src/components/goods/Review.vue
  src/components/promotion/PromotionList.vue
  src/components/promotion/PromotionSave.vue
  src/router/goods.js
  src/router/promotion.js
Labels: feat, refactor

#75 feat: 프로모션 상세 조회 및 수정 기능 api 연동
  src/components/promotion/PromotionDetail.vue
  src/components/promotion/PromotionGoodsAddModal.vue
  src/components/promotion/PromotionList.vue
  src/router/promotion.js
Labels: feat

#79 feat: 날짜별 상품 매출 증감률 백엔드 연동
  src/stores/apiClient.js
  src/views/Home.vue
Labels: feat

#82 feat: 프로모션 등록시 일정 등록 자동화 구현
  src/components/goods/GoodsList.vue
  src/components/promotion/PromotionSave.vue
  src/views/Home.vue
Labels: feat, refactor

#77 Feat: 프로모션 분석 통계 구현 #74
  src/components/promotion/PromotionAnalysis.vue
Labels: feat

#83 feat: 팀 채팅 화면 디자인 개선
  src/views/chat/ChatHome.vue
  src/views/teamspace/TeamSpaceHome.vue
Labels: feat

#87 fix: 지금까지의 프론트 오류 해결
  src/components/goods/GoodsAnalysis.vue
  src/components/goods/GoodsChart.vue
  src/components/goods/GoodsCompare.vue
  src/components/goods/PromotionList.vue
  src/components/promotion/PromotionAnalysis.vue
  src/components/teamspace/TeamBoardSave.vue
  src/router/teamspace.js
Labels: fix

#88 feat: 프로모션 분석 검색 기능 구현
  src/components/promotion/PromotionAnalysis.vue
Labels: feat

#90 feat: 연관검색어 드롭다운 구현
  src/components/goods/GoodsList.vue
Labels: feat

#94 feat: 팀스페이스 프론트 개선
  src/components/teamspace/TeamChat.vue
  src/router/index.js
  src/router/teamspace.js
  src/stores/auth.js
  src/views/chat/TeamChat.vue
  src/views/teamspace/TeamSpaceHome.vue
Labels: fix, feat

#96 feat: 프로모션 종류 관리 모달 구현
  src/components/promotion/PromotionList.vue
  src/components/promotion/PromotionTypeModal.vue
  src/stores/apiClient.js
Labels: feat, refactor

#100 feat: 상품 목록 페이징 추가
  src/components/goods/GoodsList.vue
Labels: feat

#97 feat: 프로모션 분석 검색 기능 버그 수정 #85
  src/components/promotion/PromotionAnalysis.vue
Labels: fix

#106 feat: SSE 기반의 알림 시스템 구현
  package-lock.json
  package.json
  src/assets/icons/heart.png
  src/components/common/Header.vue
  src/plugins/fontawesome.js
  src/router/index.js
  src/stores/auth.js
  src/stores/sse.js
Labels: feat, refactor

#107 refactor: css 수정
  src/components/promotion/PromotionTypeModal.vue
Labels: refactor

#98 refactor: userList 페이징 처리 추가
  src/views/admin/UserList.vue
Labels: refactor

#102 feat: 관리자만 관리자 페이지 이동
  src/router/admin.js
Labels: feat

#109 refactor: 모달 효과 추가
  src/components/admin/CreateUserModal.vue
  src/components/admin/UpdateUserModal.vue
  src/components/promotion/PromotionGoodsAddModal.vue
  src/components/promotion/PromotionTypeModal.vue
  src/views/Home.vue
Labels: refactor

#112 refactor: 프로모션 분석 그래프 기능 리팩토링 완료 #85
  src/components/promotion/PromotionAnalysis.vue
Labels: refactor

#115 feat: QnA 상세 화면에서 답변 화면도 추가로 구현
  src/components/board/qna/QnaDetail.vue
Labels: feat, refactor

#117 feat: 홈 화면 상품명 클릭 시 상품 분석 화면 이동
  src/components/goods/GoodsAnalysis.vue
  src/views/Home.vue
Labels: feat

#120 feat: 프로모션 목록 조회 페이징 처리 구현
  package-lock.json
  src/components/promotion/PromotionList.vue
  src/views/Home.vue
Labels: feat, refactor

#122 feat: 공지사항 페이지 등록, 수정, 삭제 관리자 권한 설정
  src/components/promotion/PromotionTypeModal.vue
  src/router/board.js
  src/views/board/InformList.vue
Labels: refactor

#124 refactor: 공지사항, FAQ 관리자만 수정, 삭제 가능하도록 설정
  src/components/board/faq/FaqDetail.vue
  src/components/board/inform/InformDetail.vue
  src/router/board.js
  src/views/board/FaqList.vue
Labels: refactor

#127 feat: 상품 매출 증감률 모달창 추가
  src/views/Home.vue
Labels: feat

#125 feat: 프로모션 분석 그래프 기능 완료 #85
  src/components/promotion/PromotionAnalysis.vue
Labels: refactor

#130 feat: 워크스페이스 구현
  src/components/common/Header.vue
  src/components/teamspace/TeamBoardDetail.vue
  src/components/workspace/CreateChatModal.vue
  src/components/workspace/WorkBoard.vue
  src/components/workspace/WorkChat.vue
  src/router/index.js
  src/router/workspace.js
  src/views/workspace/WorkSpaceHome.vue
Labels: feat, refactor

#137 refactor: EventSource 요청시 액세스 만료시 재발급 과정 추가
  src/stores/sse.js
Labels: feat, refactor

#134 refactor: 팀일정은 팀장만 설정 가능하도록 변경
  src/components/common/Header.vue
  src/views/Home.vue
Labels: refactor

#138 feat: 프로모션 알림 기능 프론트 구현
  src/components/common/Header.vue
  src/components/promotion/PromotionNotiModal.vue
  src/components/promotion/PromotionNotiSend.vue
  src/router/promotion.js
Labels: feat

#143 chore: 상품, 프로모션 분석 워크스페이스 등록 수정
  src/components/capture/CaptureModal.vue
  src/components/goods/GoodsAnalysis.vue
  src/components/promotion/PromotionAnalysis.vue
Labels: chore

#145 chore: 이미지 클릭 시 확대 보기 추가
  src/components/workspace/WorkBoardDetail.vue
Labels: chore

#147 chore: 모달창 애니메이션 효과 적용
  src/components/capture/CaptureModal.vue
  src/components/workspace/WorkBoardDetail.vue
Labels: chore

#148 feat: 상품 분석 화면에서 컴포넌트 추가
  src/components/goods/AiReview.vue
  src/components/goods/AprioriTable.vue
  src/components/goods/GoodsAnalysis.vue
  src/components/goods/GoodsCompare.vue
Labels: feat, refactor

#149 feat: 프로모션 고객별 추천 재실행 플라스크 연동 구현 #135
  src/components/promotion/PromotionNotiSend.vue
Labels: feat

#151 feat: 깃허브 액션 추가
  .github/workflows/main.yml
Labels: feat

#154 refactor: 이미지 관련 페이지 모두 리팩토링
  src/components/board/editor/BoardEditor.vue
  src/components/board/editor/ImageManagement.vue
  src/components/board/inform/InformDetail.vue
  src/components/board/inform/InformSave.vue
  src/components/board/inform/InformUpdate.vue
  src/components/board/qna/QnaDetail.vue
  src/components/board/qna/QnaSave.vue
  src/components/board/qna/QnaUpdate.vue
  src/components/common/Header.vue
  src/components/goods/AiReview.vue
  src/components/goods/AprioriTable.vue
  src/components/goods/GoodsChart.vue
  src/components/goods/PromotionList.vue
  src/components/teamspace/TeamBoardDetail.vue
  src/components/teamspace/TeamBoardSave.vue
  src/components/workspace/WorkBoardDetail.vue
  src/components/workspace/WorkBoardSave.vue
  src/components/workspace/WorkBoardUpdate.vue
  src/views/Home.vue
  src/views/board/FaqList.vue
  src/views/user/Login.vue
Labels: refactor

#156 refactor: 프로모션 분석 페이지 CSS 조정 및 편의 기능 추가, 버그 수정
  src/components/promotion/PromotionAnalysis.vue
Labels: refactor

#164 refactor: cloudfront 캐시 무효화 추가
  .github/workflows/main.yml
Labels: refactor

#166 feat: 채팅 파일 전송 구현 #165 SSP-77
  src/components/workspace/WorkChat.vue
Labels: feat

#159 refactor: 프로모션 분석 페이지 CSS 추가 및 편의 기능 추가 #158
  src/components/promotion/PromotionAnalysis.vue
  src/components/promotion/PromotionNotiSend.vue
Labels: chore

#161 refactor: 프로모션 알림, QnA 답변 등록 알림 추가, 알림 모두 삭제 추가
  src/components/board/qna/QnaDetail.vue
  src/components/common/Header.vue
  src/components/promotion/PromotionSave.vue
  src/stores/sse.js
  src/views/Home.vue
Labels: feat, refactor
