Repository code-4-u/beauty-4-u-FE, pull requests merged in 2025-01, with the labels that each got.

#170 refactor: 배포 로직 수정
  .github/workflows/main.yml
  src/components/workspace/WorkChat.vue
  src/main.js
  src/stores/apiClient.js
  src/stores/sse.js
  src/views/user/Login.vue
  vite.config.js
Labels: feat, refactor

#171 refactor: sse.js 수정
  src/stores/sse.js
Labels: refactor

#172 refactor: 로컬 개발 환경용 url 추가
  src/components/workspace/WorkChat.vue
  src/stores/apiClient.js
  src/stores/sse.js
  src/views/user/Login.vue
Labels: refactor

#174 style: 공지사항 스타일 수정
  src/views/board/InformList.vue
Labels: style

#176 style: qna 화면 스타일 수정
  src/views/board/QnaList.vue
Labels: style

#178 style: faq 화면 스타일 수정
  src/views/board/FaqList.vue
Labels: style

#180 fix: 워크보드 이미지 미리보기 수정
  src/components/capture/CaptureModal.vue
  src/components/workspace/WorkBoard.vue
  src/components/workspace/WorkBoardDetail.vue
  src/stores/apiClient.js
Labels: fix

#183 fix: 프로모션 알림 전송 버그 수정
  src/components/promotion/PromotionNotiSend.vue
Labels: fix

#186 refactor: 프로모션 목록 ui 변경
  src/components/goods/PromotionList.vue
Labels: feat

#187 refactor: 채팅 화면 수정
  src/components/workspace/CreateChatModal.vue
  src/components/workspace/CreateChatRoomModal.vue
  src/components/workspace/ImagePreviewModal.vue
  src/components/workspace/InviteUserModal.vue
  src/components/workspace/ParticipantListModal.vue
  src/components/workspace/WorkBoardUpdate.vue
  src/components/workspace/WorkChat.vue
Labels: refactor

#191 feat: 채팅 화면 프론트 개선
  src/components/workspace/InviteUserModal.vue
  src/components/workspace/WorkChat.vue
Labels: feat

#195 feat: 채팅 프론트 화면 수정
  src/components/workspace/CreateChatRoomModal.vue
  src/components/workspace/InviteUserModal.vue
  src/components/workspace/ParticipantListModal.vue
  src/components/workspace/WorkChat.vue
Labels: feat

#196 chore: 프로모션 분석 UI 개선
  src/components/promotion/PromotionAnalysis.vue
Labels: chore

#197 fix: 채팅 프론트 화면 오류 수정
  src/components/workspace/ParticipantListModal.vue
  src/components/workspace/WorkChat.vue
Labels: fix, feat

#198 fix: https 환경에서 웹소켓 경로 수정
  src/components/workspace/WorkChat.vue
Labels: fix

#199 fix: 이미지 다운로드 캐쉬 이슈 해결
  src/components/workspace/WorkChat.vue
Labels: fix

#201 refactor: 프로모션 알림 발송 프로모션 검색 창 UI 개선 #200
  src/components/promotion/PromotionNotiModal.vue
Labels: refactor

#202 test: 프론트 cicd 테스트
  src/views/Home.vue
Labels: test

#204 refactor: 디자인 및 라우터 리팩토링
  src/components/common/Header.vue
  src/components/promotion/PromotionAnalysis.vue
  src/router/admin.js
  src/router/analysis.js
  src/router/board.js
  src/router/customer.js
  src/router/goods.js
  src/router/promotion.js
  src/router/teamspace.js
  src/router/workspace.js
  src/stores/apiClient.js
  src/stores/auth.js
  src/stores/sse.js
Labels: feat, refactor

#207 프로모션 관리 프로모션 종류 관리 스크롤 추가
  src/components/promotion/PromotionTypeModal.vue
Labels: chore

#206 feat: 유저 초대시 새로고침 하도록 수정
  src/components/workspace/WorkBoard.vue
  src/components/workspace/WorkChat.vue
Labels: feat, chore

#208 chore: 웹소켓 불필요한 로그 제거
  src/components/workspace/WorkChat.vue
Labels: chore

#209 chore: 유저 정보 불러오기
  src/components/workspace/WorkChat.vue
Labels: chore
